name: mindr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  audio_waveforms: ^1.0.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  http: ^1.1.0
  iconsax: ^0.0.8
  introduction_screen: ^3.1.12
  permission_handler: ^11.0.1
  provider: ^6.1.2
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/calendar.gif
    - assets/images/notes.gif
    - assets/images/reminder.gif
    - assets/images/icons/google.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
